/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
declare module "@drincs/pixi-vn/characters" {
    interface PixivnCharacterIds {
        "mc": never;
        "gatekeeper": never;
        "steward": never;
    }
}
declare module "@drincs/pixi-vn/narration" {
    interface PixivnLabelIds {
        "second_part": never;
        "second_part_omen": never;
        "second_part_end": never;
        "start": never;
        "start_memory": never;
        "start_hall": never;
    }
}
declare module "@drincs/pixi-vn/canvas" {
    interface PixivnBundleIds {
        "audio": never;
        "/": never;
    }
    interface PixivnAssetAliasIds {
        "bgm_medieval_hall": never;
        "sfx_gate_creak": never;
        "sfx_rain_ambience": never;
        "sfx_torch_crackle": never;
        "background_main_menu": never;
    }
}
export const characterIds = ["mc","gatekeeper","steward"] as const;
export const characterIdsEnum = {"mc":"mc","gatekeeper":"gatekeeper","steward":"steward"} as const;
export const labelIds = ["second_part","second_part_omen","second_part_end","start","start_memory","start_hall"] as const;
export const labelIdsEnum = {"second_part":"second_part","second_part_omen":"second_part_omen","second_part_end":"second_part_end","start":"start","start_memory":"start_memory","start_hall":"start_hall"} as const;
export const bundleIds = ["audio","/"] as const;
export const bundleIdsEnum = {"audio":"audio","/":"/"} as const;
export const assetAliasIds = ["bgm_medieval_hall","sfx_gate_creak","sfx_rain_ambience","sfx_torch_crackle","background_main_menu"] as const;
export const assetAliasIdsEnum = {"bgm_medieval_hall":"bgm_medieval_hall","sfx_gate_creak":"sfx_gate_creak","sfx_rain_ambience":"sfx_rain_ambience","sfx_torch_crackle":"sfx_torch_crackle","background_main_menu":"background_main_menu"} as const;
