/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
declare module "@drincs/pixi-vn/canvas" {
    interface PixivnBundleIds {
        "audio": never;
        "/": never;
    }
    interface PixivnAssetAliasIds {
        "bgm_medieval_hall": never;
        "sfx_gate_creak": never;
        "sfx_rain_ambience": never;
        "sfx_torch_crackle": never;
        "background_main_menu": never;
    }
}
export const characterIds = [] as const;
export const characterIdsEnum = {} as const;
export const labelIds = [] as const;
export const labelIdsEnum = {} as const;
export const bundleIds = ["audio","/"] as const;
export const bundleIdsEnum = {"audio":"audio","/":"/"} as const;
export const assetAliasIds = ["bgm_medieval_hall","sfx_gate_creak","sfx_rain_ambience","sfx_torch_crackle","background_main_menu"] as const;
export const assetAliasIdsEnum = {"bgm_medieval_hall":"bgm_medieval_hall","sfx_gate_creak":"sfx_gate_creak","sfx_rain_ambience":"sfx_rain_ambience","sfx_torch_crackle":"sfx_torch_crackle","background_main_menu":"background_main_menu"} as const;
